name: flutter_portfolio
description: Flutter project to showcase learning

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  audioplayers: ^0.20.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
  fonts:
    - family: LobsterTwo
      fonts:
        - asset: fonts/LobsterTwo-Regular.ttf
        - asset: fonts/LobsterTwo-Italic.ttf
          style: italic
        - asset: fonts/LobsterTwo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/LobsterTwo-Bold.ttf
          weight: 700
    - family: ArimaMadurai
      fonts:
        - asset: fonts/ArimaMadurai-Regular.ttf
        - asset: fonts/ArimaMadurai-Bold.ttf
          weight: 700
        - asset: fonts/ArimaMadurai-ExtraLight.ttf
          weight: 200